### ISSUE TITLE
No TinyMCE/buttons to click on for bold etc

### ISSUE THREAD

**Issue by Ipstenu** [rmccue/RotorMD#2]
Related?

Error: call_user_func_array() [function.call-user-func-array]: First argument is expected to be a valid callback, 'Rotor_MarkdownEditor::after_wp_tiny_mce' was given in /home/elftest/plugins.elftest.net/wp-includes/plugin.php on line 403

**Comment by rmccue** [comment]
Should be fixed by ce47e58d45e628e924c3b4d38ed582b8c4e911b7 ?

**Comment by rmccue** [comment]
At least, the error should be. The quicktags are intentionally removed to simplify the editor.
